ARG NODE_VERSION
FROM node:${NODE_VERSION}

WORKDIR /usr/src/app
# COPY package*.json ./

# RUN npm install --location=global npm
# RUN npm install
# RUN vue upgrade


## Ressource pour installer un nouveau projet nestjs
# npm install --location=global @nestjs/cli
# nest new .
# npm run start:dev